///////////////////////////////////////////////////////////////////////////
// ComponentConfig.h, component configuration parameters.
//
// Initially generated by the component wizard. Feel free to manually edit.
///////////////////////////////////////////////////////////////////////////

// Component framework type
#define BON2COMPONENT

// COM UUID-s, names and progID
#define TYPELIB_UUID "07643176-D9BD-4D62-B6B8-CB1EC6D2B8D8"
#define TYPELIB_NAME "MGA Interpreter TypeLibrary (EasyGC)"
#define COCLASS_UUID "61014CAD-F546-4AA5-BB7C-F0FAFC644A74"
#define COCLASS_NAME "MGA Interpreter CoClass (EasyGC)"
#define COCLASS_PROGID "MGA.Interpreter.EasyGC"

#define COCLASS_UUID_EXPLODED1  0x61014cad
#define COCLASS_UUID_EXPLODED2   0xf546
#define COCLASS_UUID_EXPLODED3   0x4aa5
#define COCLASS_UUID_EXPLODED4   0xbb
#define COCLASS_UUID_EXPLODED5   0x7c
#define COCLASS_UUID_EXPLODED6   0xf0
#define COCLASS_UUID_EXPLODED7   0xfa
#define COCLASS_UUID_EXPLODED8   0xfc
#define COCLASS_UUID_EXPLODED9   0x64
#define COCLASS_UUID_EXPLODED10  0x4a
#define COCLASS_UUID_EXPLODED11  0x74


// This name will appear in the popup window for interpreter selection.
#define COMPONENT_NAME _T("EasyGC")


// This text will appear in the toolbar icon tooltip and in the menu.
#define TOOLTIP_TEXT _T("EasyGC Interpreter")

// This macro determines the component type (addon vs. interpreter):
#define GME_INTERPRETER

// The name of the paradigm(s). The GME will use this component
// for this paradigm. Separate the names of paradigms by commas.
#define PARADIGM_INDEPENDENT


#define BON_ICON_SUPPORT

// not defined: #define BON_CUSTOM_TRANSACTIONS

#define REGISTER_SYSTEMWIDE
